# Generated by Django 6.0.5 on 2026-05-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_attendancerecord_feerecord_resultrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='feerecord',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
