# Generated by Django 6.0.5 on 2026-05-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_feerecord_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultrecord',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
