# Generated by Django 6.0.7 on 2026-08-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_academy_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, choices=[('ICS', 'ICS'), ('Medical', 'Medical'), ('Non-Medical', 'Non-Medical')], max_length=20),
        ),
    ]
