# Generated by Django 6.0.8 on 2026-08-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_alter_student_section_attendancesession_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendancesessionentry',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_session_student'),
        ),
    ]
